/* editions.js — Around the Seneya data */

var EDITIONS = {
  talking: { name:'Talking Stage', ar:'مرحلة التعرف', badge:'🥰 Getting to Know · مرحلة التعرف', icon:'🥰' },
  couples: { name:'Couples',       ar:'العلاقة',      badge:'💑 Growing Together · النمو معاً',   icon:'💑' },
  married: { name:'Married',       ar:'المتزوجون',    badge:'👑 Forever & Always · الأبد معاً',   icon:'👑' },
  friends: { name:'Friends',       ar:'الأصدقاء',     badge:'👯 Ride or Die · أصدقاء الروح',      icon:'👯' },
  spicy:   { name:'18+ Unfiltered',ar:'بدون تصفية',   badge:'🔥 Adults Only · للبالغين فقط',      icon:'🔥' },
  stillus: { name:'Still Us',      ar:'مازلنا نحن',  badge:'❤️ Found Our Way Back · رجعنا لبعضياتنا', icon:'❤️' },
  engaged:     { name:'Engaged',      ar:'المخطوبون',        badge:'💍 Our Forever Begins · بدايتنا الأبدية',  icon:'💍' },
  secretfiles: { name:'Secret Files', ar:'الملفات السرية',  badge:'🕵️ Spill It All · قول كلشي',              icon:'🕵️' },
  family:      { name:'Family',       ar:'العائلة',          badge:'🏡 Closer Together · معاً أقوى',            icon:'🏡' },
  betweenus:    { name:'Between Us',   ar:'بيناتنا',     badge:'🌙 The Real Talks · الكلام الحقيقي',      icon:'🌙' },
  overthinkers: { name:'Overthinkers', ar:'المكترين',    badge:'🧠 The 3AM Edition · نسخة الـ3 صباح',     icon:'🧠' },
  healing:      { name:'Healing',      ar:'الشفاء',      badge:'🌧 After the Pain · بعد الألم',             icon:'🌧' },
  solo:         { name:'Solo Edition', ar:'بوحدك',        badge:'🌙 Self Talks · كلام الروح',                icon:'🌙' },
  masks:        { name:'Masks',        ar:'الأقنعة',      badge:'🎭 Who Are You Really? · شكون نتا حقيقة؟',  icon:'🎭' },
  loveyourself: { name:'Love Yourself', ar:'حب نفسك',     badge:'🌷 Soft & Worthy · ناعم ويستحق',             icon:'🌷' },
  future:       { name:'Future',        ar:'المستقبل',    badge:'✨ The Life You Dream · الحياة اللي كتحلم',  icon:'✨' },
  redflags:     { name:'Red & Green Flags', ar:'العلامات',   badge:'🚩 Love Opinions · آراء في الحب',           icon:'🚩' },
  girlsnight:   { name:'Girls Night',       ar:'ليلة البنات', badge:'💋 Girlhood Energy · طاقة البنات',           icon:'💋' },
  whoknows:     { name:'Who Knows Me Best?', ar:'شكون كيعرفني؟', badge:'🍟 Test Your People · اختبر ناسك',          icon:'🍟' },
  firstimpact:  { name:'First Impression',   ar:'الانطباع الأول', badge:'👀 Seen vs Real · الظاهر والحقيقة',         icon:'👀' },
  artist:       { name:'Artist Edition',     ar:'نسخة الفنانين',  badge:'🎨 Creative Souls · أرواح مبدعة',            icon:'🎨' },
  free50:       { name:'The Free 50',        ar:'خمسون سؤال',     badge:'🆓 One Night · ليلة واحدة',                  icon:'🆓' },
};

var CAT_SHORT = {
  soft:'Soft', real:'Real', psych:'Mind', between:'Lines', power:'Test',
  soft_talking:'Soft', real_talking:'Real', psych_talking:'Mind', between_talking:'Lines', power_talking:'Test',
  soft_couples:'Soft', real_couples:'Real', psych_couples:'Mind', between_couples:'Lines', power_couples:'Test',
  distance_su:'Distance', stayed_su:'Stayed', unsaid_su:'Unsaid', patterns_su:'Patterns', choosing_su:'Choosing', final_su:'This Time',
  desires_talking:'Curious', desires_couples:'Intimacy',
  desires_married:'Desires', spicy_part1:'18+ I', spicy_part2:'18+ II',
  spicy_part3:'18+ III', spicy_part4:'18+ IV',
  future_talking:'Future', future_couples:'Family',
  future_married:'Legacy', friendship_deep:'Friends', challenges_friends:'Dare',
  soft_friends:'Soft', real_friends:'Real', psych_friends:'Mind', between_friends:'Between', power_friends:'Test',
  soft_engaged:'Soft', real_engaged:'Real', psych_engaged:'Mind', between_engaged:'Lines', power_engaged:'Test',
  promise_engaged:'Promise', home_engaged:'Home',
  secrets_sf:'Secrets', laughs_sf:'Laughs', likely_sf:'Likely', cringe_sf:'Cringe', chaos_sf:'Chaos',
  energy_fam:'Energy', chaos_fam:'Chaos', feels_fam:'Feels', night_fam:'Night', forever_fam:'Forever',
  between_bt:'Between', debates_bt:'Debates', midnight_bt:'Midnight', real_bt:'Identity',
  mind_3am:'3AM Mind', insecurities_ot:'Fears', mindvsheart_ot:'Mind vs Heart', healing_ot:'Healing',
  whathurt_h:'What Hurt You', healingprocess_h:'Healing', neversay_h:'Never Say', newversion_h:'New You', softness_h:'Softness',
  whoami_s:'Who Are You', thoughts_s:'Thoughts', healing_s:'Letting Go', future_s:'Future You', selflove_s:'Self Love',
  showpeople_m:'The Mask', hiddenself_m:'Hidden Self', maskexists_m:'Why Masks', exhaustion_m:'Exhaustion', unmasking_m:'Unmasking',
  seeing_ly:'Seeing You', softenergy_ly:'Soft Energy', healself_ly:'Heal Yourself', innerworld_ly:'Inner World', becoming_ly:'Becoming',
  dreamlife_f:'Dream Life', lovenext_f:'Future Love', fears_f:'Fears', success_f:'Success', letters_f:'Dear Future Me',
  turnoffs_rf:'Turn Offs', greenflags_rf:'Green Flags', toxic_rf:'Toxic Truths', standards_rf:'Standards', opinions_rf:'Midnight Opinions',
  girlhood_gn:'Girlhood', feminine_gn:'Feminine', love_gn:'Love & Crushes', neversay_gn:'Unspoken', forever_gn:'Forever Girls',
  littlethings_wk:'Little Things', mindread_wk:'Inside My Mind', loveread_wk:'Love & Me', realme_wk:'The Real Me', memories_wk:'Our Memories',
  howseeme_fi:'How They See Me', perception_fi:'Perception Game', relimpress_fi:'Relationship Impressions', truthvibe_fi:'Truth vs Perception',
  identity_ar:'My Artist Soul', block_ar:'Creative Block', emotions_ar:'Art & Emotions', dreams_ar:'Artistic Dreams',
  fun_free50:'Fun & Chaos', love_free50:'Love', deep_free50:'Deep', group_free50:'Group', final_free50:'Final',
};
